# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import gkb_parser_pb2 as gkb__parser__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gkb_parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GkbParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/gkb_parser.GkbParser/Health',
                request_serializer=gkb__parser__pb2.HealthRequest.SerializeToString,
                response_deserializer=gkb__parser__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Parse = channel.unary_unary(
                '/gkb_parser.GkbParser/Parse',
                request_serializer=gkb__parser__pb2.ParseRequest.SerializeToString,
                response_deserializer=gkb__parser__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.ParseSummary = channel.unary_unary(
                '/gkb_parser.GkbParser/ParseSummary',
                request_serializer=gkb__parser__pb2.ParseSummaryRequest.SerializeToString,
                response_deserializer=gkb__parser__pb2.ParseSummaryResponse.FromString,
                _registered_method=True)


class GkbParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Parse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GkbParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=gkb__parser__pb2.HealthRequest.FromString,
                    response_serializer=gkb__parser__pb2.HealthResponse.SerializeToString,
            ),
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=gkb__parser__pb2.ParseRequest.FromString,
                    response_serializer=gkb__parser__pb2.ParseResponse.SerializeToString,
            ),
            'ParseSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseSummary,
                    request_deserializer=gkb__parser__pb2.ParseSummaryRequest.FromString,
                    response_serializer=gkb__parser__pb2.ParseSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gkb_parser.GkbParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gkb_parser.GkbParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GkbParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gkb_parser.GkbParser/Health',
            gkb__parser__pb2.HealthRequest.SerializeToString,
            gkb__parser__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gkb_parser.GkbParser/Parse',
            gkb__parser__pb2.ParseRequest.SerializeToString,
            gkb__parser__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gkb_parser.GkbParser/ParseSummary',
            gkb__parser__pb2.ParseSummaryRequest.SerializeToString,
            gkb__parser__pb2.ParseSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
